version: '3.8'


services:
  db:
    image: postgres:alpine
    container_name: postgres-sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: smonitoring

  api-tester:
      container_name: api-tester
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '8081:8080'
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smonitoring
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=123456
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      depends_on:
        - db

  grafana:
      image: grafana/grafana
      container_name: grafana_api-tester
      restart: unless-stopped
      volumes:
          - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      ports:
        - "80:3000"
      depends_on:
        - db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - db
